### PR TITLE
Add podspec for cocoapods support on iOS

### PR DESCRIPTION
**Pull request by tulusheg**

### CODE REVIEW

**Comment by henninghall** [comment]
Great, thanks for your contribution! Do you bother making a small improvement by making the version and licence field dynamic? like this for examle: [lottie-react-native.podspec ](https://github.com/react-community/lottie-react-native/blob/master/lottie-react-native.podspec )

**Comment by henninghall** [comment]
Also, I would prefer this email address: henning.hall@hotmail.com

**Comment by Dalamar** [comment]
Please merge it.

**Comment by henninghall** [comment]
@Dalamar I'll solve this tonight if @tulusheg hasn't fixed it before then.

**Comment by henninghall** [comment]
Fixed by https://github.com/henninghall/react-native-date-picker/commit/cc627142510c6a8a27c75217218be2c59c676e40 and released in version `2.0.2` 🍾

**Pull request closed without merging**
