### PR TITLE
Fix missing import related to issue #437

### PR DESCRIPTION
**Pull request by gustavoggs**
#437

### CODE REVIEW

**Comment by fobos531** [comment]
It may also be a good idea to change imports of other react headers as well since expo now requires them to be imported in `#import <React/*.h>` form.

See: https://github.com/expo/expo/issues/15622#issuecomment-997141629

**Comment by gustavoggs** [comment]
Thanks @fobos531 update it to follow the suggestion

**Comment by jake-ruth** [comment]
let's get this merrrrged boys :)

**Comment by henninghall** [comment]
Thanks a lot for the PR! 

The reason for not merging this directly is that I remember that "angle bracket"-imports were causing some issues in the past. I want to test this change properly, find those issues and figure out if this change might cause the same problems. I will probably have time to do that within a few weeks. If anyone could help me out that would be really helpful. In that case please post the findings in this thread 🙏 

Until then I would recommend you to use [patch package](https://github.com/ds300/patch-package) to get this fix into your project. Thanks for your patience!

**Comment by jake-ruth** [comment]
Just a heads up, the first commit here seems to work for me and fixes the issue, but the second commit is still throwing the same error for me. Using expo 0.44 and RN 0.64.3

**Comment by gustavoggs** [comment]
Yes @jake-ruth I did updated it based on the comment, but didn't tested. Now I went back and checked what is inside each import and tested it here. The lastest commit I think that we have the correct imports and it worked correctly in my tests, the same for the first commit but it had one extra import that was not needed.

The second commit was not working properly.

**Comment by gustavoggs** [comment]
Expo is moving back in their change as it caused problem in multiple libraries, but good to check if it is not good to continue with this PR.

expo/expo#15622 (comment)

**Comment by gustavoggs** [comment]
As you can see here: https://github.com/lufinkey/react-native-events/pull/9#issuecomment-1008311384 it is good to continue with the changes, I will see if there is other parts that we need to update and if needed I will update this PR

**Comment by henninghall** [comment]
Since this doesn't seem to be an issue in the latest Expo version I'll close this.

**Pull request closed without merging**
