### PR TITLE
Removed dependency to moment.js

### PR DESCRIPTION
**Pull request by kentandersen**
Replaces moment.js with vanilla addMinutes as discussed in #173

### CODE REVIEW

**Comment by henninghall** [comment]
Hi! Thanks a lot for the PR, this seems like a great improvement! Could you have a look at the errors from the end-to-end tests? 

https://github.com/henninghall/react-native-date-picker/actions/runs/259320124

[Failing tests (4).zip](https://github.com/henninghall/react-native-date-picker/files/5241230/Failing.tests.4.zip)

I also have to run some daylight saving tests locally before merging. 
Thanks again!

**Comment by kentandersen** [comment]
Removed a leftover `.toDate()` which fixes the the end-to-end tests. Had som issues with random failures from timeout etc, but it works now 😎

**Comment by kentandersen** [comment]
Bump 😊, any chance to get this merged?

**Comment by henninghall** [comment]
@kentandersen It is now released in v3.2.4 🎉

**Pull request merged**
