### PR TITLE
add import to fix builds failing on iOS

### PR DESCRIPTION
**Pull request by 1mike12**
fixes https://github.com/henninghall/react-native-date-picker/issues/506 and https://github.com/henninghall/react-native-date-picker/issues/474

### CODE REVIEW

**Comment by henninghall** [comment]
Thanks for the PR! Do you know if it also solves https://github.com/henninghall/react-native-date-picker/issues/474 ?

**Comment by AndreiBehel** [comment]
@henninghall can you merge and release new version with this fix?

**Comment by gabrieldonadel** [comment]
Any updates on this?

**Comment by slade77777** [comment]
Can anyone merge it?

**Comment by 1mike12** [comment]
@henninghall  yes, this is the exact same fix as mentioned in #474

**Pull request merged**
