### PR TITLE
[android]fix:"DatePickerManager" was not found in the UIManager

### PR DESCRIPTION
**Pull request by JChord**
autolink doc: [https://github.com/react-native-community/cli/blob/master/docs/autolinking.md](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md)
issues: #40 #44 #107

### CODE REVIEW

**Comment by henninghall** [comment]
Closing this one since I cannot reproduce any problems with auto-linking with later versions of React Native. Haven't found any other packages that have used this solution either.

**Comment by MOODOOW** [comment]
Capture d’écran 2021-01-16 à 17 58 22

I was waiting for this PR to be merged since it seems to be able to solve my issue.  Any other way to fix it ?

**Comment by JSharles** [comment]
Capture d’écran 2021-01-16 à 17 58 22

I was waiting for this PR to be merged since it seems to be the solution to my problem.

Is there any other way to resolve this issue ?

**Comment by henninghall** [comment]
@JSharles Which React Native version do you run?

**Comment by JSharles** [comment]
> @JSharles Which React Native version do you run?

@henninghall  16.13.1

**Comment by henninghall** [comment]
That's the react version, whats the react native version?

**Comment by JSharles** [comment]
My bad... The RN version is 0.63.2

**Comment by henninghall** [comment]
You seem to have this issue on both android and ios. 

1. Have you run `pod install` and `react-native run-ios` or equal on iOS? 
2. Have you run `react-native run-android` and a gradle clean on android?

**Comment by JSharles** [comment]
Indeed, the issue occurs on both platforms.

Every other Date Picker libraries available work fine, but yours is the only one to offer an ios clone for Android.

I am rather a beginner regarding software development so it could be something that I forgot to do. 

Here's my the steps I followed : 

1 - installed the lib
2 - npx react-native link
3- cd ios && pod install && cd ..
4- run-ios and run-android

**Comment by henninghall** [comment]
You shouldn't need to run `react-native link` on react native versions after 0.59 so maybe that's messing things up. Try restoring the project to before installing this lib and try without the link command. Otherwise it looks like you're doing everything right!

**Comment by brtdv** [comment]
I have the same issue with Expo. 

I simply executed `yarn add react-native-date-picker` && `expo start`, which gives me the same error. I also tried removing my node_modules folder and reinstalling everything with `yarn install`.

**Comment by Balaji2810** [comment]
> I have the same issue with Expo.
> 
> I simply executed `yarn add react-native-date-picker` && `expo start`, which gives me the same error. I also tried removing my node_modules folder and reinstalling everything with `yarn install`.
> 
> **Edit**: My bad, I didn't notice Expo was not supported.

Any solutions for expo????

**Comment by NazoSnare** [comment]
@henninghall is this now working on expo? I am having the same issue on the expogo emulator and app on my physical device

**Pull request closed without merging**
