### PR TITLE
Add prop contentFont for android

### PR DESCRIPTION
**Pull request by dumihi313**
I added contentFont for custom typeface in content text.
It just work for android

### CODE REVIEW

**Comment by henninghall** [comment]
Thanks for the PR! what do you mean by "content" in this context of "contentFont"?

**Comment by dumihi313** [comment]
The end objective is to call super.setContentTextTypeface()

so this 'content' is get from this word setContentTextTypeface(), Does it make sense?

**Comment by henninghall** [comment]
Thanks once again, some questions:
1. Can you give an example on how to use this? 
2. Should the prop be the name of the font, a path to a font or a font file? 
3. Where should the font file be placed? 
4. Does it support built in fonts and/or custom ones?
5. Can we support the android native variant?
6. Can we support iOS?

**Comment by dumihi313** [comment]
Thanks once again, some questions:

1. Can you give an example on how to use this?
`        <DatePicker
          .......
          date={date}
          onDateChange={setDate}
          contentFont="fonts/NunitoSans-Italic.ttf"
        />
`
2. Should the prop be the name of the font, a path to a font or a font file?
It should be location path like "fonts/NunitoSans-Italic.ttf"
3. Where should the font file be placed?
fonts in assets android
image
4. Does it support built in fonts and/or custom ones?
yes, as I show on fonts in assets android
5. Can we support the android native variant?
just only android native variant
6, Can we support iOS?
As I checked, lib use ios native lib so we can not adjust font family, font size as well ...

**Comment by henninghall** [comment]
iOS clone is no longer supported, this feature could still be useful for the nativeAndroid variant

**Pull request closed without merging**
