### PR TITLE
[android][new_arch][fix]: pass timestamp string instead of iso string…

### PR DESCRIPTION
**Pull request by badrey**
A workaround for runtime error with new architecture enabled on Android https://github.com/henninghall/react-native-date-picker/issues/840

### CODE REVIEW

**Comment by RamProg** [comment]
This solution helped me to fix crashes on Android with the new architecture. Can it be integrated in the next release?

**Comment by mateoabrbt** [comment]
@henninghall this PR those indeed fix the crash that occur on Android on the new arch should also be tested on a non-new arch app to see if its brake anything.

**Comment by NonozgYtb** [comment]
@henninghall
A working exemple in my app :

```javascript
import DatePicker from "react-native-date-picker";

const Select = () => {
    const [date, setDate] = useState(new Date());

    return <DatePicker date={date} onDateChange={setDate} />;
};
```

**Comment by rak-dev** [comment]
@henninghall  can you please explain little bit more on  how to use your solution

**Comment by 29er** [comment]
i am still having this issue using     "react-native-date-picker": "git+https://github.com/badrey/react-native-date-picker.git#new-arc-fix". exact same error on Android
please help. !

**Pull request closed without merging**
