### PR TITLE
fix: RN 73 compatibility

### PR DESCRIPTION
**Pull request by felipecsl**
https://github.com/react-native-community/discussions-and-proposals/issues/671

### CODE REVIEW

**Comment by felipecsl** [comment]
@henninghall the `gradle.properties` change is needed because on AGP8, `BuildConfig` is no longer enabled by default, which breaks the build. Adding this flag reenables it.

The unit tests are failing exactly for this reason, you need to add the same flag here https://github.com/henninghall/react-native-date-picker/blob/master/examples/Rn072/android/gradle.properties

**Comment by felipecsl** [comment]
There was another issue related to the namespace not matching the `R` class package. Just updated which should fix it

**Comment by felipecsl** [comment]
Interesting. this did pop up with a project I was trying to upgrade, but we put the upgrade on hold for now so I'm no longer actively working on it.
I'd say let's wait to see if more users will run into this issue, no rush to merge yet I think.

**Comment by rvera** [comment]
Are your fixes on the latest version? Somehow I'm still getting a `Namespace not specified` error.

(Trying to update to RN 73, using v4.3.5 of this lib)

**Comment by felipecsl** [comment]
These changes have been not merged yet, so I assume no

**Comment by farfalletonde** [comment]
> @rvera could you please share an example repo where the issue is present? As far as I know RN 0.73 is supported without this PR and an example repo with RN 0.73 with the the picker is provided in the example folder of this repo.

Unable to resolve module expo-constants from node_modules/react-native-date-picker/src/installationError.js: expo-constants could not be found within the project or in these directories:

This is what I get after upgrading from 0.72.12 to 0.73.0
Cannot share my repo however I only followed these steps: https://react-native-community.github.io/upgrade-helper/?from=0.72.12&to=0.73.0

**Comment by VelocityPulse** [comment]
Is this pull request abandonned ?

**Comment by henninghall** [comment]
@VelocityPulse please read comment https://github.com/henninghall/react-native-date-picker/pull/726#issuecomment-1850087497 

Can you provide a repo where this is actually an issue? Then we can look into it again.

**Comment by cachac** [comment]
Needed for RN 73 - 74... 

If you want a workaround, need to update your: gradle-wrapper.properties

Change gradle version:
distributionUrl=https\://services.gradle.org/distributions/gradle-8.8-all.zip

And prebuild (EXPO):

npx expo prebuild --no-install  && npx expo run:android

**Comment by henninghall** [comment]
I'll close this PR until I become aware of situations where the absence of this change is an issue.

**Pull request closed without merging**
