### PR TITLE
onDateChange docs update

### PR DESCRIPTION
**Pull request by hlspablo**
make clear that onDateChange only fires when in inline mode

### CODE REVIEW

**Comment by henninghall** [comment]
Thanks @hlspablo!

**Comment by darboleda-paycargo** [comment]
what is the alternative for modal mode?

**Comment by hlspablo** [comment]
@darboleda-paycargo inline mode, look: https://github.com/henninghall/react-native-date-picker

**Comment by darboleda-paycargo** [comment]
found it. was looking for the onConfirm, since using modal. thank you

**Pull request merged**
