### PR TITLE
Hide keyboard in IOS when clicking date

### PR DESCRIPTION
**Pull request by huydosgtech**

### CODE REVIEW

**Comment by henninghall** [comment]
Hi, thanks for the PR. We have previously been closing a similar one https://github.com/henninghall/react-native-date-picker/pull/461. I would like to know how we can motivate this change. Isn't this a feature we want to keep according to apples intended design?

**Comment by huydosgtech** [comment]
Thank you for you response, Could you create a prop for this feature?

**Comment by henninghall** [comment]
In what scenario would it be useful for the user to remove the keyboard input possibility?

**Comment by huydosgtech** [comment]
it would be useful for user when the time picker is in bottom sheet, and it's bottom of screen. And keyboard cannot overlay the time picker

**Comment by henninghall** [comment]
If bottomsheet is implemented correctly I believe the keyboard should push the bottomsheet up. Like what happens when using `modal={true}`. Or do I miss the point? 🙂 

https://github.com/henninghall/react-native-date-picker/assets/1652607/3c231c1b-fece-4057-91d6-84cfb31d9f63

**Comment by huydosgtech** [comment]
Ah, I see. Thank you for your explaining

**Pull request closed without merging**
