### PR TITLE
larger touchable area between wheels

### PR DESCRIPTION
**Pull request by henninghall**
Fixes https://github.com/henninghall/react-native-date-picker/issues/145

### CODE REVIEW

**Comment by mars-lan** [comment]
While not 100% sure, it seems that this PR may have broken the ability to set the width of the picker on Android (for iOS clone), e.g. the following code used to work on `3.0.3` but had no effect on `3.1.0`

```
<DatePicker style={{width: WIDTH}} />
```

**Comment by mars-lan** [comment]
@henninghall ^^^

**Comment by henninghall** [comment]
@ttristan @mars-lan This should be fixed in v3.2.1 🙂

**Comment by mars-lan** [comment]
@henninghall it's fixed indeed. Thanks for the quick response.

**Pull request merged**
